export { default as Home } from './home/Home'
export { default as Scoreboard } from './scoreboard/Scoreboard'
export { default as Help } from './help/Help'
export { default as Bubble } from './bubble/Bubble'
export { default as Win } from './gameOver/Win'
export { default as Loss } from './gameOver/Loss'
